/*
Greg Francis
Cpsc 101
Professor Dukes
Bull and Cows Game
*/

/*Algorithm:
1) declare variables to hold values for bulls, cows, and other various counters.
2) output directions on how to play the game.
3) input data from user on code length
4) ask the user to enter a code
5) create arrays to hold code and the guess entered by the user
6) compare arrays to see if the values are equal or not
7) if the values are equal return bull
8) if the values are not equal see if they match another number in the code and return bull
9) if the user guesses less numbers correct than the code length, ask the user to try again.
10) if the user guessed all numbers correct then they win!
*/

#include <stdio.h>

#include <math.h>

int main ( void )
{
	
	int num = 0; // user defined code length

	int g[6] = {0,0,0,0,0,0};  // array that holds the code entered by the user

	int c[6] = {0,0,0,0,0,0};  // array that generates the code

	int conv[6] = {0,0,0,0,0,0}; // array that seperate the code entered by the user into single digits

	int code; // variable that defines which spot in array g							

	int guess = 0; // variable that defines how many digits the code array will generate						

	int bulls = 0; // counter for amount of bulls the user has guessed 						

	int count = 0;  // variable used to either restart, or end game

	int max = 0; // variable used to hold values for a counter in the conversion array

        int cows = 0;  // variable used to count the amount of cows entered by the user							

        int n = 0; // variable used as a counter within loops

	int q = 0; // another counter variable used in the loop to seperate digits

	int pguess = 0; // variable that holds the users guess

	int s = 0; // another counter variable
	
	while (count == 0) // loop that controls the replay of the game
	{

		printf("How many digits do you want the code to be? " );  

	        scanf("%i" , &num);         //takes the user input and assigns that value to num                                    

		count = 0;                  //makes sure count is 0 each time the inner loops run
		
		if((num >= 2) && (num <= 6))//if statement that decides whether or not the user entered a valid number for code length
				
		{

        		printf("Guess the code : ");  

        		

			
			while( cows <  num)	// loop that keeps the user guessing as long as cows is less than code length				
		
			{
				bulls = 0;      // resets all values to zero for each time the user guesses a code
				cows = 0; 
				g[0] = 0;
                                g[1] = 0;
                                g[2] = 0;
                                g[3] = 0;
                                g[4] = 0;
                                g[5] = 0;
                                c[0] = 0;
                                c[1] = 0;
                                c[2] = 0;
                                c[3] = 0;
                                c[4] = 0;
                                c[5] = 0;
                                
				scanf("%d" , &pguess); // user guess at the code generated by the computer

				for(code = 0, q = 1; code < num; code++ ) 	// loop that starts the seperation of digits process
								       	
				{
					g[code] = pguess/pow(10,num-q);
					
					q++;
											
					
				}
		
				for (guess = 0; guess <  num ; guess++)  	//loop that generates the code
		
				{
		
					c[guess] = guess + 1;  			
										
				}
	
				

                                for (max = 5,n = 5; max >= 0; max--)            // loop that converts array g to single digits 
				
				{
					
					conv[max] = (g[n]%10);
					n--;
					
				}	
				
				
			
				for (n = 0; n < num; n++)			//loop that checks for cows
			
				{
					
					if(conv[n] == c[n]) 			
				
					{

					      cows++;			
					
				
					}
				}



                                 for (n = 0; n < num; n++)                    // loop that checks for bulls

                                 {

                                         if (conv[n] != c[n])
                                         {
                                              for (s = 5; s >= 0; s--)
                                              {
                                                    if ((conv[n] == c[s])&&( s != n))
                                                    {
                                                              bulls++;
                                                    }   

                                               }
                                          }
                                  }


											
			if (cows != num)      //condition that tells the user to try again
			
			{
				printf("\tNope! %d cows, %d bulls. \n", cows,bulls);	
				printf("Guess the code: ");
			}
			
						
			
			if(cows == num)         // condition that makes the user win

			{

				printf("You won! \n");

			}

	
	}
	}
	
	
	else    //condition if the user does not enter a valid code length
	
	{

	      printf("Not a valid digit, Please try again! \n");

	}


	     printf("Type 0 to continue or 1 to quit : "); // prompts the user to quit or play again!
	     scanf("%d" , &count);
	     bulls = 0;
	     cows = 0;	
	}
	return ( 0 );
}

