/*
Greg Francis
Cpsc 101
Professor Dukes
Bull and Cows Game
*/

/*Algorithm:
1) declare variables to hold values for bulls, cows, and other various counters.
2) output directions on how to play the game.
3) input data from user on code length
4) ask the user to enter a code
5) create arrays to hold code and the guess entered by the user
6) compare arrays to see if the values are equal or not
7) if the values are equal return bull
8) if the values are not equal see if they match another codeLengthber in the code and return bull
9) if the user guesses less codeLengthbers correct than the code length, ask the user to try again.
10) if the user guessed all codeLengthbers correct then they win!
*/

#include <stdio.h>
#include <math.h>
#include <time.h>
#include <stdlib.h>


int main( void )
{
	int keepPlaying = 1;
	int codeLength;					// user defined code length
	int bulls = 0; 					// counter for amount of bulls the user has guessed 						
	int restart = 0; 				// variable used to either restart, or end game
	int cows = 0; 					// variable used to count the amount of cows entered by the user							
	int pguess = 0; 				// variable that holds the users guess
	srand(time(NULL));   			// should only be called once
	while(keepPlaying == 1) 				// loop that controls the replay of the game
	{
		printf("How many digits do you want the code to be? " );  
	    scanf("%d" , &codeLength);         						//takes the user input and assigns that value to codeLength                                    
		if((codeLength >= 2) && (codeLength <= 6))				//if statement that decides whether or not the user entered a valid codeLength for code length
		{
        	int secretCode[codeLength];
			for(int i = 0; i < codeLength; i++)
			{
				secretCode[i] = rand() % 10;
				printf("%d", secretCode[i]);
			}
			
			printf("Guess the code : ");  
			while(cows < codeLength)							// loop that keeps the user guessing as long as cows is less than code length				
			{
				scanf("%d" , &pguess); 							// user guess at the code generated by the computer
				int userGuess[codeLength];
				for(int i = 0, mod = 10; i < codeLength; i++ ) 				// loop that starts the seperation of digits process
				{
					userGuess[codeLength - 1] = pguess % mod;
					mod = mod * 10;
					printf("%d", userGuess[codeLength -1]);
				}
				for (int i = 0; i < codeLength; i++)					//loop that checks for cows
				{
					if(userGuess[i] == secretCode[i]) 			
					{
						cows++;			
					}
					for(int ii = 1; ii < codeLength ; ii++)
					{
						if(userGuess[i] == secretCode[ii])
						{
							bulls++;
						}
					}
				}
				
				if (cows != codeLength)      						//condition that tells the user to try again
				{
					printf("\tNope! %d cows, %d bulls. \n", cows,bulls);	
					printf("Guess the code: ");
				}
				if(cows == codeLength)         					// condition that makes the user win
				{
					printf("You won! \n");
				}
			}
		}
		else    											//condition if the user does not enter a valid code length
		{
			printf("Not a valid digit, Please try again! \n");
		}
		while(restart != 1 || restart != 0)
		{
			printf("Type 0 to continue or 1 to quit : "); 		// prompts the user to quit or play again!
			scanf("%d" , &restart);
			if(restart == 1)
			{
				keepPlaying = 0;
			}
			if(restart == 0)
			{
				bulls = 0;
				cows = 0;	
			}
		}
	}
	return ( 0 );
}

